# Generated by Django 6.1 on 2026-08-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='fa-utensils', help_text='FontAwesome or Lucide icon class e.g. fa-pizza-slice, fa-burger, fa-cocktail', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, default='General Inquiry', max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tagline', models.CharField(help_text='e.g. Best Combo for 3 Friends!', max_length=200)),
                ('items_included', models.TextField(help_text='Bullet points or summary of included items')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='deals/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Atmosphere', 'Atmosphere'), ('Kitchen', 'Kitchen Prep')], default='Food', max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Friday Special: Authentic Kabuli Pulao', max_length=200)),
                ('day_of_week', models.CharField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Everyday', 'Everyday')], default='Friday', max_length=50)),
                ('description', models.TextField(default='Slow-cooked tender beef with aromatic rice, sweet raisins, and roasted almonds. Prepared fresh every Friday!')),
                ('price', models.DecimalField(decimal_places=2, default=799.0, max_digits=8)),
                ('original_price', models.DecimalField(decimal_places=2, default=999.0, max_digits=8)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='specials/')),
                ('is_active', models.BooleanField(default=True)),
                ('countdown_hours', models.IntegerField(default=12, help_text='Countdown hours for special offer badge')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('spicy_level', models.IntegerField(choices=[(1, 'Mild'), (2, 'Medium'), (3, 'Hot'), (4, 'Extra Hot')], default=1)),
                ('flavor_tags', models.CharField(default='Street Style, Chef Special', help_text='Comma-separated flavor tags e.g. Spicy, Cheese Loaded, Crunchy', max_length=200)),
                ('has_size_options', models.BooleanField(default=False, help_text='Enable Small / Medium / Large & Crust options for Pizzas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
